### ISSUE TITLE
Support ESlint v7

### ISSUE THREAD

**Issue by GuillaumeRahbari** [PayFit/eslint-config-payfit#63]
Peer dependencies that need updates before this library can be sure to support eslint v7 :

- [x] @typescript-eslint/eslint-plugin
- [x] @typescript-eslint/parser
- [ ] eslint-config-airbnb (airbnb/javascript#2223)
- [ ] eslint-config-airbnb-base (airbnb/javascript#2223)
- [x] eslint-config-prettier
- [x] eslint-plugin-eslint-comments
- [x] eslint-plugin-import
- [x] eslint-plugin-jest
- [ ] eslint-plugin-jsx-a11y (https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/698) waiting for release
- [x] eslint-plugin-no-unsanitized
- [x] eslint-plugin-node
- [x] eslint-plugin-react
- [x] eslint-plugin-react-hooks
- [x] eslint-plugin-security
- [ ] eslint-plugin-sonarjs (SonarSource/eslint-plugin-sonarjs#162)
- [x] eslint-plugin-xss

**Comment by stefanKuijers** [comment]
eslint-plugin-import (https://github.com/benmosher/eslint-plugin-import/issues/1796)
